name: 'Markdown'
description: 'Render a TCG Markdown document'
inputs:
  input-md:
    description: 'The name of the Markdown file to render'
    required: true
  output-pdf:
    description: 'The name of the rendered PDF file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--self-contained'
    - '--template=eisvogel.latex'
    - '--filter=mermaid-filter'
    - '--resource-path=.:/resources'
    - '--data-dir=/resources'
    - '--toc'
    - '--variable=block-headings'
    - '--metadata=titlepage:true'
    - '--metadata=titlepage-background:/resources/img/cover.png'
    - '--metadata=logo:/resources/img/tcg.png'
    - '--metadata=titlepage-rule-height:0'
    - '--metadata=colorlinks:true'
    - '--metadata=toc-own-page:true'
    - '--metadata=contact:admin@trustedcomputinggroup.org'
    - '--from=markdown+implicit_figures'
    - '--to=pdf'
    - '${{ inputs.input-md }}'
    - '--output=${{ inputs.output-pdf }}'
