name: 'Markdown'
description: 'Render a TCG Markdown document'
inputs:
  input-md:
    description: 'The name of the Markdown file to render'
    required: true
  output-pdf:
    description: 'The name of the rendered PDF file'
    required: true
runs:
  using: 'composite'
  steps:
    # If the action is being used from a tag, use the corresponding prebuilt container.
    # Detect this by stripping off 'refs/tags/v' from the ref used for the action and comparing it to the ref.
    # Otherwise, build the container fresh.
    - id: get-container
      env:
        ACTION_REF: ${{ github.action_ref }}
      run: |
        TAG=${ACTION_REF#refs/tags/v}
        if [[ "$TAG" == "$ACTION_REF" ]]; then
        echo ::set-output name=container::Dockerfile
        else
        echo ::set-output name=container::docker://ghcr.io/trustedcomputinggroup/markdown:r$TAG
        fi
    - uses: ${{ steps.get-container.outputs.container }}
      with:
        args:
          - '--template=eisvogel.latex'
          - '--resource-path=/resources'
          - '--data-dir=/resources'
          - '--toc'
          - '--variable=block-headings'
          - '--metadata=titlepage:true'
          - '--metadata=titlepage-background:/resources/img/cover.png'
          - '--metadata=logo:/resources/img/tcg.png'
          - '--metadata=titlepage-rule-height:0'
          - '--metadata=colorlinks:true'
          - '--metadata=toc-own-page:true'
          - '--metadata=contact:admin@trustedcomputinggroup.org'
          - '--from=markdown'
          - '--to=pdf'
          - '${{ inputs.input-md }}'
          - '--output=${{ inputs.output-pdf }}'
