name: 'Markdown'
description: 'Render a TCG Markdown document'
inputs:
  input-md:
    description: 'The name of the Markdown file to render'
    required: true
  output-pdf:
    description: 'The name of the rendered PDF file'
    required: true
  output-docx:
    description: 'The name of the rendered DOCX file'
  output-tex:
    description: 'The name of the rendered TEX file'
runs:
  using: 'composite'
  steps:
    - run: build.sh --puppeteer --pdf=${{ inputs.output-pdf }} ${{ inputs.input-md }}
      shell: sh

    - run: build.sh --puppeteer --latex=${{ inputs.output-tex }} ${{ inputs.input-md }}
      shell: sh
      if: ${{ inputs.output-tex }}

    - run: build.sh --puppeteer --docx=${{ inputs.output-docx }} ${{ inputs.input-md }}
      shell: sh
      if: ${{ inputs.output-docx }}
