name: 'Markdown'
description: 'Render a TCG Markdown document'
inputs:
  input-md:
    description: 'The name of the Markdown file to render'
    required: true
  output-pdf:
    description: 'The name of the rendered PDF file'
    required: true
  output-docx:
    description: 'The name of the rendered DOCX file'
runs:
  using: 'composite'
  steps:
    # let the container take ownership of the repo dir, in case the user wants to check in the results
    # workaround to https://github.com/actions/runner/issues/2033
    - run: chown -R $(id -u):$(id -g) $PWD
      shell: sh
    # There are some configuration dependencies required for Mermaid.
    # They have to be in the current directory.
    - run: |
        cat << EOF > ./.puppeteer.json
        {
            "executablePath": "/usr/bin/chromium-browser",
            "args": [
                "--no-sandbox",
                "--disable-setuid-sandbox"
            ]
        }
        EOF
      shell: sh
    # GitHub Mermaid doesn't recognize the full ```{.mermaid ...} attributes-form
    # Pandoc doesn't recognized mixed ```mermaid {...} form
    # Hack: use sed to transform the former to the latter so everyone is happy
    - run: >
        sed -i
        's/```mermaid *{/```{.mermaid /g'
        ${{ inputs.input-md }}
      shell: sh
    # \newpage is rendered as the string "\newpage" in GitHub markdown.
    # Transform horizontal rules into \newpages.
    # Exception: the YAML front matter of the document, so undo the instance on the first line.
    - run: >
        sed -i
        's/^---$/\\newpage/g;1s/\\newpage/---/g'
        ${{ inputs.input-md }}
      shell: sh
    # Grab the date from the front matter and generate the full date and year.
    - run: |
        DATE=$(grep date: ${{ inputs.input-md }} | head -n 1 | cut -d ' ' -f 2)
        YEAR=$(date --date=$DATE +%Y)
        echo "::set-output name=year::$YEAR"
        DATE_ENGLISH=$(date --date=$DATE "+%B %-d, %Y")
        echo "::set-output name=date-english::$DATE_ENGLISH"
      shell: bash
      id: date
    - run: >
        pandoc
        --embed-resources
        --standalone
        --template=eisvogel.latex
        --filter=mermaid-filter
        --filter=pandoc-crossref
        --resource-path=.:/resources
        --data-dir=/resources
        --toc
        --variable=block-headings
        --variable=table-use-row-colors
        --metadata=date-english:"${{ steps.date.outputs.date-english }}"
        --metadata=year:"${{ steps.date.outputs.year }}"
        --metadata=titlepage:true
        --metadata=titlepage-background:/resources/img/cover.png
        --metadata=logo:/resources/img/tcg.png
        --metadata=titlepage-rule-height:0
        --metadata=colorlinks:true
        --metadata=toc-own-page:true
        --metadata=contact:admin@trustedcomputinggroup.org
        --from=markdown+implicit_figures
        --to=pdf
        ${{ inputs.input-md }}
        --output=${{ inputs.output-pdf }}
      shell: sh
      env:
        MERMAID_FILTER_THEME: "forest"
        MERMAID_FILTER_FORMAT: "pdf"
    - run: >
        pandoc
        --embed-resources
        --standalone
        --filter=mermaid-filter
        --filter=pandoc-crossref
        --resource-path=.:/resources
        --data-dir=/resources
        --from=markdown+implicit_figures
        --reference-doc=/resources/templates/tcg_template.docx
        --to=docx
        ${{ inputs.input-md }}
        --output=${{ inputs.output-docx }}
      shell: sh
      if: ${{ inputs.output-docx }} 
      env:
        MERMAID_FILTER_THEME: "forest"
        MERMAID_FILTER_FORMAT: "pdf"
