name: 'Markdown'
description: 'Render a TCG Markdown document'
inputs:
  input-md:
    description: 'The name of the Markdown file to render'
    required: true
  output-pdf:
    description: 'The name of the rendered PDF file'
    required: true
runs:
  using: 'composite'
  steps:
    # There are some configuration dependencies required for Mermaid.
    # They have to be in the current directory.
    - run: |
        cat << EOF > ./.mermaid-config.json
        {
            "theme": "forest",
            "caption": "true",
            "format": "svg",
            "width": 1600
        }
        EOF
      shell: sh
    - run: |
        cat << EOF > ./.puppeteer.json
        {
            "executablePath": "/usr/bin/chromium-browser",
            "args": [
                "--no-sandbox",
                "--disable-setuid-sandbox"
            ]
        }
        EOF
      shell: sh
    - run: >
        pandoc
        --embed-resources
        --standalone
        --template=eisvogel.latex
        --filter=mermaid-filter
        --filter=pandoc-crossref
        --resource-path=.:/resources
        --data-dir=/resources
        --toc
        --variable=block-headings
        --metadata=titlepage:true
        --metadata=titlepage-background:/resources/img/cover.png
        --metadata=logo:/resources/img/tcg.png
        --metadata=titlepage-rule-height:0
        --metadata=colorlinks:true
        --metadata=toc-own-page:true
        --metadata=contact:admin@trustedcomputinggroup.org
        --from=markdown+implicit_figures
        --to=pdf
        ${{ inputs.input-md }}
        --output=${{ inputs.output-pdf }}
      shell: sh
