name: 'Markdown'
description: 'Render a TCG Markdown document'
inputs:
  input-md:
    description: 'The name of the Markdown file to render'
    required: true
  output-pdf:
    description: 'The name of the rendered PDF file'
  output-html:
    description: 'The name of the rendered HTML file'
  output-docx:
    description: 'The name of the rendered DOCX file'
  output-tex:
    description: 'The name of the rendered TEX file'
runs:
  using: 'composite'
  steps:
    # let the container take ownership of the repo dir, in case the user wants to check in the results
    # workaround to https://github.com/actions/runner/issues/2033
    - run: chown -R $(id -u):$(id -g) $PWD
      shell: sh
    - run: >
        /usr/bin/build.sh
        $( [ -n "${{ inputs.output-pdf }}" ] && echo --pdf=${{ inputs.output-pdf }} )
        $( [ -n "${{ inputs.output-html }}" ] && echo --html=${{ inputs.output-html }} )
        $( [ -n "${{ inputs.output-docx }}" ] && echo --docx=${{ inputs.output-docx }} )
        $( [ -n "${{ inputs.output-tex }}" ] && echo --latex=${{ inputs.output-tex }} )
        ${{ inputs.input-md }}
      shell: sh
