name: 'Markdown'
description: 'Render a TCG Markdown document'
inputs:
  input-md:
    description: 'The name of the Markdown file to render'
    required: true
  output-pdf:
    description: 'The name of the rendered PDF file'
    required: true
  output-docx:
    description: 'The name of the rendered DOCX file'
  output-tex:
    description: 'The name of the rendered TEX file'
runs:
  using: 'composite'
  steps:
    # let the container take ownership of the repo dir, in case the user wants to check in the results
    # workaround to https://github.com/actions/runner/issues/2033
    - run: chown -R $(id -u):$(id -g) $PWD
      shell: sh
    - run: >
        /usr/bin/build.sh
        --puppeteer
        --pdf=${{ inputs.output-pdf }}
        ${{ inputs.input-md }}
      shell: sh
      env:
        MERMAID_FILTER_THEME: "forest"
        MERMAID_FILTER_FORMAT: "pdf"
    - run: >
        /usr/bin/build.sh
        --puppeteer
        --latex=${{ inputs.output-tex }}
        ${{ inputs.input-md }}
      shell: sh
      if: ${{ inputs.output-tex }} 
      env:
        MERMAID_FILTER_THEME: "forest"
        MERMAID_FILTER_FORMAT: "pdf"
    - run: >
        /usr/bin/build.sh
        --puppeteer
        --pdf=${{ inputs.output-pdf }}
        --docx=${{ inputs.output-docx }}
        ${{ inputs.input-md }}
      shell: sh
      if: ${{ inputs.output-docx }} 
      env:
        MERMAID_FILTER_THEME: "forest"
        MERMAID_FILTER_FORMAT: "pdf"
