name: release latest

on:
  release:
    types: [published]

jobs:
  tag-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Tag latest
        uses: EndBug/latest-tag@v1.5.0
