name: render samples

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  render-samples:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/trustedcomputinggroup/pandoc:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run the action on sample1
        uses: ./
        with:
          input-md: sample1.md
          output-pdf: sample1.pdf
          output-docx: sample1.docx
          output-tex: sample1.tex
          output-html: sample1.html

      - name: Run the action on sample2
        uses: ./
        with:
          input-md: sample2.md
          output-pdf: sample2.pdf
          output-docx: sample2.docx
          output-html: sample2.html

      - name: Run the action on sample3
        uses: ./
        with:
          input-md: sample3.md
          output-pdf: sample3.pdf

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: samples
          path: |
            sample*.docx
            sample*.tex
            sample*.pdf
            sample*.html

      - name: Check in latest render
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate latest PDF
          file_pattern: sample*.pdf
        if: github.event_name != 'pull_request'
